# Generated by Django 4.1.5 on 2023-07-29 05:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserMessages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type_groups', models.BooleanField(default=True)),
                ('messages', models.ManyToManyField(blank=True, to='UserMessages.usermessages')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользовательская группа',
                'verbose_name_plural': 'Пользовательские группы',
            },
        ),
    ]
